use DataWarehouse;
--1)data explorations
select distinct sales  from gold.fact_sales

select * from INFORMATION_SCHEMA.TABLES
--2)dimesions exploration
select min(sales_order_date) as min_order_date,
max(sales_order_date) as max_order_date,
datediff(year,min(sales_order_date),max(sales_order_date) ) as difference
from gold.fact_sales

select * from gold.dim_customers
--3)date exploration

select min(birthdate)as oldest_customer,
datediff(year,min(birthdate),getdate()) as oldest_age,
max(birthdate) as youngest_customer,
datediff(year,max(birthdate),getdate())as youngest_age
from gold.dim_customers

--4)measure exploration

--find the total sales 
select sum(sales) as total_sales from gold.fact_sales

--find how many items are sold
select sum(quantity) as total_quantity from gold.fact_sales

--find the average selling price 
select avg(price) as average_price from gold.fact_sales

--find the total number of orders
select count(distinct order_number) as total_orders from gold.fact_sales

--find the total number of products 
select count( product_key) as total_products from gold.fact_sales
select count(distinct product_name) as total_products from gold.dim_products
select * from gold.fact_sales

--find the total number of customers
select count(customer_key) as total_customers from gold.dim_customers

--find the total cutsomers who have placed orders 
select count(distinct customer_key) as cutomer_orders from gold.fact_sales

--but instead of writing these key metrics differently we will generate a reort of all the key metrics together
select 'total_sales' as measure_name ,sum(sales) as measure_value from gold.fact_sales
union all 
select 'total quantity' as measure_name ,sum(quantity)  from gold.fact_sales
union all 
select 'average_ price' as measure_name ,avg(price)  from gold.fact_sales
union all 
select 'total orders' as meaure_name ,count(distinct order_number)  from gold.fact_sales

--5)magnitude analysis

--find the total customers by gender 
select gender,
count(customer_key) as total_customers 
from gold.dim_customers
group by gender
order by total_customers desc

--find the total customers by countries 
select country,
count(customer_key) as total_customers 
from gold.dim_customers
group by country
order by total_customers desc

--find the total producta by category
select category ,
count(product_key) as total_products from gold.dim_products
group by category
order by total_products desc

--what is the average cost for each category 
select category,
AVG(cost) as average_cost from gold.dim_products
group by category
order by average_cost desc

select * from gold.fact_sales
--what is total revenue generated for each category 
select p.category,sum(f.sales) as total_revenue from gold.fact_sales f left join gold.dim_products p on f.product_key = p.product_key
group by p.category
order by total_revenue desc

--what is the total revenue generated by each customers
select c.customer_key,
c.first_name,
c.last_name,
sum(f.sales) as total_revenue 
from
gold.fact_sales f left join gold.dim_customers c 
on f.customer_key=c.customer_key
group by c.customer_key,
c.first_name,
c.last_name
order by total_revenue desc

--what is the distribution of the total items sold in the countries
select 
c.country,
sum(sales) as total_revenue 
from
gold.fact_sales f left join gold.dim_customers c 
on f.customer_key=c.customer_key
group by c.country
order by total_revenue desc

--6)ranking
--select top 5 products that generte highest revenue
select  top 5 
p.product_name,sum(f.sales) as total_revenue
from gold.fact_sales f left join gold.dim_products p
on f.product_key =p.product_key
group by p.product_name 
order by total_revenue desc


   --can be done using the window function like row_number()
   select * from(
   select  
	p.product_name,sum(f.sales) as total_revenue,
	row_number() over(order by sum(f.sales)desc) as ranks
	from gold.fact_sales f left join gold.dim_products p
	on f.product_key =p.product_key
	group by p.product_name ) t
	where ranks <= 5
	
